# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\Bob\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\cluz3\forms\cluz_form_distribution.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_distributionDialog(object):
    def setupUi(self, distributionDialog):
        distributionDialog.setObjectName("distributionDialog")
        distributionDialog.resize(728, 540)
        self.logoLabel = QtWidgets.QLabel(distributionDialog)
        self.logoLabel.setGeometry(QtCore.QRect(-10, 20, 120, 380))
        self.logoLabel.setText("")
        self.logoLabel.setPixmap(QtGui.QPixmap(":/images/images/setup_logo.png"))
        self.logoLabel.setObjectName("logoLabel")
        self.horizontalLayoutWidget = QtWidgets.QWidget(distributionDialog)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(290, 480, 221, 51))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.okButton = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.okButton.setMinimumSize(QtCore.QSize(0, 24))
        self.okButton.setObjectName("okButton")
        self.horizontalLayout.addWidget(self.okButton)
        self.cancelButton = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.cancelButton.setMinimumSize(QtCore.QSize(0, 24))
        self.cancelButton.setObjectName("cancelButton")
        self.horizontalLayout.addWidget(self.cancelButton)
        self.featLabel = QtWidgets.QLabel(distributionDialog)
        self.featLabel.setGeometry(QtCore.QRect(140, 20, 561, 24))
        self.featLabel.setMinimumSize(QtCore.QSize(421, 24))
        self.featLabel.setObjectName("featLabel")
        self.featListWidget = QtWidgets.QListWidget(distributionDialog)
        self.featListWidget.setGeometry(QtCore.QRect(140, 50, 561, 171))
        self.featListWidget.setSelectionMode(QtWidgets.QAbstractItemView.MultiSelection)
        self.featListWidget.setObjectName("featListWidget")
        self.filePathlabel = QtWidgets.QLabel(distributionDialog)
        self.filePathlabel.setGeometry(QtCore.QRect(140, 390, 541, 16))
        self.filePathlabel.setMinimumSize(QtCore.QSize(351, 16))
        self.filePathlabel.setObjectName("filePathlabel")
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(distributionDialog)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(140, 410, 561, 41))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.filePathlineEdit = QtWidgets.QLineEdit(self.horizontalLayoutWidget_2)
        self.filePathlineEdit.setMinimumSize(QtCore.QSize(0, 26))
        self.filePathlineEdit.setObjectName("filePathlineEdit")
        self.horizontalLayout_2.addWidget(self.filePathlineEdit)
        self.filePathButton = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.filePathButton.setMinimumSize(QtCore.QSize(0, 26))
        self.filePathButton.setObjectName("filePathButton")
        self.horizontalLayout_2.addWidget(self.filePathButton)
        self.verticalLayoutWidget = QtWidgets.QWidget(distributionDialog)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(150, 230, 423, 138))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.catFeatLabel = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.catFeatLabel.setMinimumSize(QtCore.QSize(421, 24))
        self.catFeatLabel.setObjectName("catFeatLabel")
        self.verticalLayout.addWidget(self.catFeatLabel)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout.addItem(spacerItem)
        self.intervalRadioButton = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        self.intervalRadioButton.setMinimumSize(QtCore.QSize(0, 24))
        self.intervalRadioButton.setChecked(True)
        self.intervalRadioButton.setObjectName("intervalRadioButton")
        self.verticalLayout.addWidget(self.intervalRadioButton)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout.addItem(spacerItem1)
        self.areaRadioButton = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        self.areaRadioButton.setMinimumSize(QtCore.QSize(0, 24))
        self.areaRadioButton.setObjectName("areaRadioButton")
        self.verticalLayout.addWidget(self.areaRadioButton)
        self.groupBox = QtWidgets.QGroupBox(distributionDialog)
        self.groupBox.setGeometry(QtCore.QRect(140, 230, 351, 141))
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.groupBox.raise_()
        self.logoLabel.raise_()
        self.horizontalLayoutWidget.raise_()
        self.featLabel.raise_()
        self.featListWidget.raise_()
        self.filePathlabel.raise_()
        self.horizontalLayoutWidget_2.raise_()
        self.verticalLayoutWidget.raise_()

        self.retranslateUi(distributionDialog)
        self.cancelButton.clicked.connect(distributionDialog.close)
        QtCore.QMetaObject.connectSlotsByName(distributionDialog)

    def retranslateUi(self, distributionDialog):
        _translate = QtCore.QCoreApplication.translate
        distributionDialog.setWindowTitle(_translate("distributionDialog", "Show distribution of features"))
        self.okButton.setText(_translate("distributionDialog", "OK"))
        self.cancelButton.setText(_translate("distributionDialog", "Cancel"))
        self.featLabel.setText(_translate("distributionDialog", "Select conservation features to display"))
        self.filePathlabel.setText(_translate("distributionDialog", "Name of shapefile that will be produced:"))
        self.filePathButton.setText(_translate("distributionDialog", "Browse"))
        self.catFeatLabel.setText(_translate("distributionDialog", "Choose legend categories"))
        self.intervalRadioButton.setText(_translate("distributionDialog", "Equal  interval"))
        self.areaRadioButton.setText(_translate("distributionDialog", "Equal area"))

import resources_rc

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    distributionDialog = QtWidgets.QDialog()
    ui = Ui_distributionDialog()
    ui.setupUi(distributionDialog)
    distributionDialog.show()
    sys.exit(app.exec_())

