# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\Bob\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\cluz3\forms\cluz_form_create.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_createDialog(object):
    def setupUi(self, createDialog):
        createDialog.setObjectName("createDialog")
        createDialog.resize(760, 454)
        createDialog.setMinimumSize(QtCore.QSize(760, 450))
        self.logoLabel = QtWidgets.QLabel(createDialog)
        self.logoLabel.setGeometry(QtCore.QRect(-10, 20, 120, 380))
        self.logoLabel.setText("")
        self.logoLabel.setPixmap(QtGui.QPixmap(":/images/images/setup_logo.png"))
        self.logoLabel.setObjectName("logoLabel")
        self.horizontalLayoutWidget = QtWidgets.QWidget(createDialog)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(310, 380, 201, 41))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.okButton = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.okButton.setMinimumSize(QtCore.QSize(0, 24))
        self.okButton.setObjectName("okButton")
        self.horizontalLayout.addWidget(self.okButton)
        self.cancelButton = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.cancelButton.setMinimumSize(QtCore.QSize(0, 24))
        self.cancelButton.setObjectName("cancelButton")
        self.horizontalLayout.addWidget(self.cancelButton)
        self.puLabel = QtWidgets.QLabel(createDialog)
        self.puLabel.setGeometry(QtCore.QRect(140, 20, 571, 16))
        self.puLabel.setObjectName("puLabel")
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(createDialog)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(140, 50, 601, 41))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.puLineEdit = QtWidgets.QLineEdit(self.horizontalLayoutWidget_2)
        self.puLineEdit.setMinimumSize(QtCore.QSize(0, 24))
        self.puLineEdit.setMaxLength(32766)
        self.puLineEdit.setObjectName("puLineEdit")
        self.horizontalLayout_2.addWidget(self.puLineEdit)
        self.puButton = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.puButton.setMinimumSize(QtCore.QSize(0, 24))
        self.puButton.setObjectName("puButton")
        self.horizontalLayout_2.addWidget(self.puButton)
        self.horizontalLayoutWidget_3 = QtWidgets.QWidget(createDialog)
        self.horizontalLayoutWidget_3.setGeometry(QtCore.QRect(140, 100, 351, 41))
        self.horizontalLayoutWidget_3.setObjectName("horizontalLayoutWidget_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_3)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.convLabel = QtWidgets.QLabel(self.horizontalLayoutWidget_3)
        self.convLabel.setMinimumSize(QtCore.QSize(111, 16))
        self.convLabel.setObjectName("convLabel")
        self.horizontalLayout_3.addWidget(self.convLabel)
        self.convLineEdit = QtWidgets.QLineEdit(self.horizontalLayoutWidget_3)
        self.convLineEdit.setMinimumSize(QtCore.QSize(0, 24))
        self.convLineEdit.setObjectName("convLineEdit")
        self.horizontalLayout_3.addWidget(self.convLineEdit)
        self.convHintLabel1 = QtWidgets.QLabel(createDialog)
        self.convHintLabel1.setGeometry(QtCore.QRect(500, 100, 241, 16))
        self.convHintLabel1.setMinimumSize(QtCore.QSize(171, 16))
        self.convHintLabel1.setObjectName("convHintLabel1")
        self.convHintLabel2 = QtWidgets.QLabel(createDialog)
        self.convHintLabel2.setGeometry(QtCore.QRect(500, 120, 251, 16))
        self.convHintLabel2.setMinimumSize(QtCore.QSize(171, 16))
        self.convHintLabel2.setObjectName("convHintLabel2")
        self.equalCheckBox = QtWidgets.QCheckBox(createDialog)
        self.equalCheckBox.setGeometry(QtCore.QRect(160, 150, 581, 24))
        self.equalCheckBox.setMinimumSize(QtCore.QSize(401, 24))
        self.equalCheckBox.setObjectName("equalCheckBox")
        self.inputLabel = QtWidgets.QLabel(createDialog)
        self.inputLabel.setGeometry(QtCore.QRect(140, 210, 601, 16))
        self.inputLabel.setObjectName("inputLabel")
        self.horizontalLayoutWidget_4 = QtWidgets.QWidget(createDialog)
        self.horizontalLayoutWidget_4.setGeometry(QtCore.QRect(140, 230, 601, 41))
        self.horizontalLayoutWidget_4.setObjectName("horizontalLayoutWidget_4")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_4)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.inputLineEdit = QtWidgets.QLineEdit(self.horizontalLayoutWidget_4)
        self.inputLineEdit.setMinimumSize(QtCore.QSize(0, 24))
        self.inputLineEdit.setObjectName("inputLineEdit")
        self.horizontalLayout_4.addWidget(self.inputLineEdit)
        self.inputButton = QtWidgets.QPushButton(self.horizontalLayoutWidget_4)
        self.inputButton.setMinimumSize(QtCore.QSize(0, 24))
        self.inputButton.setObjectName("inputButton")
        self.horizontalLayout_4.addWidget(self.inputButton)
        self.targetLabel = QtWidgets.QLabel(createDialog)
        self.targetLabel.setGeometry(QtCore.QRect(140, 280, 601, 16))
        self.targetLabel.setObjectName("targetLabel")
        self.horizontalLayoutWidget_5 = QtWidgets.QWidget(createDialog)
        self.horizontalLayoutWidget_5.setGeometry(QtCore.QRect(140, 300, 601, 51))
        self.horizontalLayoutWidget_5.setObjectName("horizontalLayoutWidget_5")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_5)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.targetLineEdit = QtWidgets.QLineEdit(self.horizontalLayoutWidget_5)
        self.targetLineEdit.setObjectName("targetLineEdit")
        self.horizontalLayout_5.addWidget(self.targetLineEdit)
        self.targetButton = QtWidgets.QPushButton(self.horizontalLayoutWidget_5)
        self.targetButton.setMinimumSize(QtCore.QSize(0, 24))
        self.targetButton.setObjectName("targetButton")
        self.horizontalLayout_5.addWidget(self.targetButton)

        self.retranslateUi(createDialog)
        self.cancelButton.clicked.connect(createDialog.close)
        QtCore.QMetaObject.connectSlotsByName(createDialog)

    def retranslateUi(self, createDialog):
        _translate = QtCore.QCoreApplication.translate
        createDialog.setWindowTitle(_translate("createDialog", "Create CLUZ files"))
        self.okButton.setText(_translate("createDialog", "OK"))
        self.cancelButton.setText(_translate("createDialog", "Cancel"))
        self.puLabel.setText(_translate("createDialog", "Select shapefile that will be used to produce the planning unit layer"))
        self.puButton.setText(_translate("createDialog", "Browse"))
        self.convLabel.setText(_translate("createDialog", "Area conversion factor"))
        self.convHintLabel1.setText(_translate("createDialog", "10000 to convert m2 to ha"))
        self.convHintLabel2.setText(_translate("createDialog", "1000000 to convert m2 to km2"))
        self.equalCheckBox.setText(_translate("createDialog", "Set cost layer as equal to planning unit area"))
        self.inputLabel.setText(_translate("createDialog", "Specify input folder where puvspr2.dat file will be created"))
        self.inputButton.setText(_translate("createDialog", "Browse"))
        self.targetLabel.setText(_translate("createDialog", "Name of target table to be created"))
        self.targetButton.setText(_translate("createDialog", "Save As"))

import resources_rc

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    createDialog = QtWidgets.QDialog()
    ui = Ui_createDialog()
    ui.setupUi(createDialog)
    createDialog.show()
    sys.exit(app.exec_())

