# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\Bob\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\cluz3\forms\cluz_form_irrep.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_irrepDialog(object):
    def setupUi(self, irrepDialog):
        irrepDialog.setObjectName("irrepDialog")
        irrepDialog.resize(610, 450)
        irrepDialog.setMinimumSize(QtCore.QSize(610, 450))
        self.logoLabel = QtWidgets.QLabel(irrepDialog)
        self.logoLabel.setGeometry(QtCore.QRect(-10, 20, 120, 380))
        self.logoLabel.setText("")
        self.logoLabel.setPixmap(QtGui.QPixmap(":/images/images/setup_logo.png"))
        self.logoLabel.setObjectName("logoLabel")
        self.horizontalLayoutWidget = QtWidgets.QWidget(irrepDialog)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(240, 360, 271, 41))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.okButton = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.okButton.setMinimumSize(QtCore.QSize(0, 24))
        self.okButton.setObjectName("okButton")
        self.horizontalLayout.addWidget(self.okButton)
        self.cancelButton = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.cancelButton.setMinimumSize(QtCore.QSize(0, 24))
        self.cancelButton.setObjectName("cancelButton")
        self.horizontalLayout.addWidget(self.cancelButton)
        self.outputCheckBox = QtWidgets.QCheckBox(irrepDialog)
        self.outputCheckBox.setGeometry(QtCore.QRect(160, 230, 401, 21))
        self.outputCheckBox.setObjectName("outputCheckBox")
        self.verticalLayoutWidget = QtWidgets.QWidget(irrepDialog)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(160, 60, 421, 79))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.allRadioButton = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        self.allRadioButton.setMinimumSize(QtCore.QSize(211, 20))
        self.allRadioButton.setChecked(True)
        self.allRadioButton.setObjectName("allRadioButton")
        self.verticalLayout.addWidget(self.allRadioButton)
        self.availableRadioButton = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        self.availableRadioButton.setMinimumSize(QtCore.QSize(211, 25))
        self.availableRadioButton.setCheckable(True)
        self.availableRadioButton.setObjectName("availableRadioButton")
        self.verticalLayout.addWidget(self.availableRadioButton)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout.addItem(spacerItem)
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(irrepDialog)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(160, 140, 421, 31))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.irrepLabel = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.irrepLabel.setObjectName("irrepLabel")
        self.horizontalLayout_2.addWidget(self.irrepLabel)
        self.irrepLineEdit = QtWidgets.QLineEdit(self.horizontalLayoutWidget_2)
        self.irrepLineEdit.setMinimumSize(QtCore.QSize(0, 24))
        self.irrepLineEdit.setObjectName("irrepLineEdit")
        self.horizontalLayout_2.addWidget(self.irrepLineEdit)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.horizontalLayout_2.addItem(spacerItem1)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.horizontalLayout_2.addItem(spacerItem2)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.horizontalLayout_2.addItem(spacerItem3)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.horizontalLayout_2.addItem(spacerItem4)
        self.horizontalLayoutWidget_3 = QtWidgets.QWidget(irrepDialog)
        self.horizontalLayoutWidget_3.setGeometry(QtCore.QRect(160, 260, 421, 31))
        self.horizontalLayoutWidget_3.setObjectName("horizontalLayoutWidget_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_3)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.outputLabel = QtWidgets.QLabel(self.horizontalLayoutWidget_3)
        self.outputLabel.setObjectName("outputLabel")
        self.horizontalLayout_3.addWidget(self.outputLabel)
        self.outputLineEdit = QtWidgets.QLineEdit(self.horizontalLayoutWidget_3)
        self.outputLineEdit.setMinimumSize(QtCore.QSize(0, 24))
        self.outputLineEdit.setObjectName("outputLineEdit")
        self.horizontalLayout_3.addWidget(self.outputLineEdit)
        self.browseButton = QtWidgets.QPushButton(self.horizontalLayoutWidget_3)
        self.browseButton.setMinimumSize(QtCore.QSize(0, 20))
        self.browseButton.setObjectName("browseButton")
        self.horizontalLayout_3.addWidget(self.browseButton)
        self.irrepRadiolabel = QtWidgets.QLabel(irrepDialog)
        self.irrepRadiolabel.setGeometry(QtCore.QRect(150, 30, 361, 16))
        self.irrepRadiolabel.setObjectName("irrepRadiolabel")

        self.retranslateUi(irrepDialog)
        self.cancelButton.clicked.connect(irrepDialog.close)
        self.outputCheckBox.clicked['bool'].connect(self.outputLineEdit.setVisible)
        self.outputCheckBox.clicked['bool'].connect(self.browseButton.setVisible)
        self.outputCheckBox.clicked['bool'].connect(self.outputLabel.setVisible)
        QtCore.QMetaObject.connectSlotsByName(irrepDialog)

    def retranslateUi(self, irrepDialog):
        _translate = QtCore.QCoreApplication.translate
        irrepDialog.setWindowTitle(_translate("irrepDialog", "Calculate irreplaceability values"))
        self.okButton.setText(_translate("irrepDialog", "OK"))
        self.cancelButton.setText(_translate("irrepDialog", "Cancel"))
        self.outputCheckBox.setText(_translate("irrepDialog", "Save irreplaceability values for each feature as a text file"))
        self.allRadioButton.setText(_translate("irrepDialog", "every planning unit being Available, ie amount of each feature conserved = 0"))
        self.availableRadioButton.setText(_translate("irrepDialog", "current portfolio, ie amount of each feature conserved =\n"
"   amount in Conserved and Earmarked planning units"))
        self.irrepLabel.setText(_translate("irrepDialog", "Field name"))
        self.outputLabel.setText(_translate("irrepDialog", "Output file"))
        self.browseButton.setText(_translate("irrepDialog", "Browse"))
        self.irrepRadiolabel.setText(_translate("irrepDialog", "Calculate summed irreplaceability values based on:"))

import resources_rc

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    irrepDialog = QtWidgets.QDialog()
    ui = Ui_irrepDialog()
    ui.setupUi(irrepDialog)
    irrepDialog.show()
    sys.exit(app.exec_())

