# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'cluz_form_convert_csv.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_convertCsvDialog(object):
    def setupUi(self, convertCsvDialog):
        convertCsvDialog.setObjectName("convertCsvDialog")
        convertCsvDialog.resize(730, 380)
        convertCsvDialog.setMinimumSize(QtCore.QSize(730, 380))
        self.logoLabel = QtWidgets.QLabel(convertCsvDialog)
        self.logoLabel.setGeometry(QtCore.QRect(-10, -10, 131, 401))
        self.logoLabel.setText("")
        self.logoLabel.setPixmap(QtGui.QPixmap(":/plugins/Cluz/icons/icons/setup_logo.png"))
        self.logoLabel.setObjectName("logoLabel")
        self.csvLabel = QtWidgets.QLabel(convertCsvDialog)
        self.csvLabel.setGeometry(QtCore.QRect(140, 20, 491, 16))
        self.csvLabel.setObjectName("csvLabel")
        self.horizontalLayoutWidget = QtWidgets.QWidget(convertCsvDialog)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(260, 320, 241, 41))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.okButton = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.okButton.setMinimumSize(QtCore.QSize(0, 22))
        self.okButton.setObjectName("okButton")
        self.horizontalLayout.addWidget(self.okButton)
        self.cancelButton = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.cancelButton.setMinimumSize(QtCore.QSize(0, 22))
        self.cancelButton.setObjectName("cancelButton")
        self.horizontalLayout.addWidget(self.cancelButton)
        self.verticalLayoutWidget = QtWidgets.QWidget(convertCsvDialog)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(160, 170, 541, 74))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.noneRadioButton = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        self.noneRadioButton.setMinimumSize(QtCore.QSize(441, 20))
        self.noneRadioButton.setObjectName("noneRadioButton")
        self.verticalLayout.addWidget(self.noneRadioButton)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout.addItem(spacerItem)
        self.userRadioButton = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        self.userRadioButton.setMinimumSize(QtCore.QSize(0, 20))
        self.userRadioButton.setObjectName("userRadioButton")
        self.verticalLayout.addWidget(self.userRadioButton)
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(convertCsvDialog)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(180, 250, 331, 31))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.convLabel = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.convLabel.setMinimumSize(QtCore.QSize(151, 20))
        self.convLabel.setObjectName("convLabel")
        self.horizontalLayout_2.addWidget(self.convLabel)
        self.convLineEdit = QtWidgets.QLineEdit(self.horizontalLayoutWidget_2)
        self.convLineEdit.setMinimumSize(QtCore.QSize(0, 20))
        self.convLineEdit.setObjectName("convLineEdit")
        self.horizontalLayout_2.addWidget(self.convLineEdit)
        self.horizontalLayoutWidget_3 = QtWidgets.QWidget(convertCsvDialog)
        self.horizontalLayoutWidget_3.setGeometry(QtCore.QRect(140, 100, 561, 41))
        self.horizontalLayoutWidget_3.setObjectName("horizontalLayoutWidget_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_3)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.idfieldLabel = QtWidgets.QLabel(self.horizontalLayoutWidget_3)
        self.idfieldLabel.setMinimumSize(QtCore.QSize(151, 16))
        self.idfieldLabel.setObjectName("idfieldLabel")
        self.horizontalLayout_3.addWidget(self.idfieldLabel)
        self.idfieldComboBox = QtWidgets.QComboBox(self.horizontalLayoutWidget_3)
        self.idfieldComboBox.setObjectName("idfieldComboBox")
        self.horizontalLayout_3.addWidget(self.idfieldComboBox)
        self.horizontalLayoutWidget_4 = QtWidgets.QWidget(convertCsvDialog)
        self.horizontalLayoutWidget_4.setGeometry(QtCore.QRect(139, 40, 561, 41))
        self.horizontalLayoutWidget_4.setObjectName("horizontalLayoutWidget_4")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_4)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.csvFileLineEdit = QtWidgets.QLineEdit(self.horizontalLayoutWidget_4)
        self.csvFileLineEdit.setObjectName("csvFileLineEdit")
        self.horizontalLayout_4.addWidget(self.csvFileLineEdit)
        self.browseButton = QtWidgets.QPushButton(self.horizontalLayoutWidget_4)
        self.browseButton.setMinimumSize(QtCore.QSize(0, 22))
        self.browseButton.setObjectName("browseButton")
        self.horizontalLayout_4.addWidget(self.browseButton)

        self.retranslateUi(convertCsvDialog)
        self.cancelButton.clicked.connect(convertCsvDialog.close)
        self.userRadioButton.toggled['bool'].connect(self.convLabel.setEnabled)
        self.userRadioButton.toggled['bool'].connect(self.convLineEdit.setEnabled)
        QtCore.QMetaObject.connectSlotsByName(convertCsvDialog)

    def retranslateUi(self, convertCsvDialog):
        _translate = QtCore.QCoreApplication.translate
        convertCsvDialog.setWindowTitle(_translate("convertCsvDialog", "Convert themes to abundance data"))
        self.csvLabel.setText(_translate("convertCsvDialog", "Select csv file to import data into Marxan"))
        self.okButton.setText(_translate("convertCsvDialog", "OK"))
        self.cancelButton.setText(_translate("convertCsvDialog", "Cancel"))
        self.noneRadioButton.setText(_translate("convertCsvDialog", "No conversion (results will be in layer measurement units)"))
        self.userRadioButton.setText(_translate("convertCsvDialog", "User defined conversion"))
        self.convLabel.setText(_translate("convertCsvDialog", "Area conversion value"))
        self.idfieldLabel.setText(_translate("convertCsvDialog", "Layer planning unit ID field name"))
        self.browseButton.setText(_translate("convertCsvDialog", "Browse"))

import resources_rc

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    convertCsvDialog = QtWidgets.QDialog()
    ui = Ui_convertCsvDialog()
    ui.setupUi(convertCsvDialog)
    convertCsvDialog.show()
    sys.exit(app.exec_())

