# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\Bob\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\cluz3\forms\cluz_form_richness.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_richnessDialog(object):
    def setupUi(self, richnessDialog):
        richnessDialog.setObjectName("richnessDialog")
        richnessDialog.resize(570, 540)
        richnessDialog.setMinimumSize(QtCore.QSize(570, 540))
        self.logoLabel = QtWidgets.QLabel(richnessDialog)
        self.logoLabel.setGeometry(QtCore.QRect(-10, 20, 120, 380))
        self.logoLabel.setText("")
        self.logoLabel.setPixmap(QtGui.QPixmap(":/images/images/setup_logo.png"))
        self.logoLabel.setObjectName("logoLabel")
        self.horizontalLayoutWidget = QtWidgets.QWidget(richnessDialog)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(200, 480, 271, 41))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.okButton = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.okButton.setMinimumSize(QtCore.QSize(0, 24))
        self.okButton.setObjectName("okButton")
        self.horizontalLayout.addWidget(self.okButton)
        self.cancelButton = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.cancelButton.setMinimumSize(QtCore.QSize(0, 24))
        self.cancelButton.setObjectName("cancelButton")
        self.horizontalLayout.addWidget(self.cancelButton)
        self.verticalLayoutWidget = QtWidgets.QWidget(richnessDialog)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(130, 330, 421, 131))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.typeLabel = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.typeLabel.setObjectName("typeLabel")
        self.verticalLayout.addWidget(self.typeLabel)
        self.typeListWidget = QtWidgets.QListWidget(self.verticalLayoutWidget)
        self.typeListWidget.setSelectionMode(QtWidgets.QAbstractItemView.MultiSelection)
        self.typeListWidget.setObjectName("typeListWidget")
        self.verticalLayout.addWidget(self.typeListWidget)
        self.gridLayoutWidget = QtWidgets.QWidget(richnessDialog)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(130, 60, 421, 251))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.countLabel = QtWidgets.QLabel(self.gridLayoutWidget)
        self.countLabel.setEnabled(False)
        self.countLabel.setMinimumSize(QtCore.QSize(0, 24))
        self.countLabel.setObjectName("countLabel")
        self.gridLayout.addWidget(self.countLabel, 1, 0, 1, 1)
        self.countLineEdit = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.countLineEdit.setEnabled(False)
        self.countLineEdit.setMinimumSize(QtCore.QSize(0, 24))
        self.countLineEdit.setObjectName("countLineEdit")
        self.gridLayout.addWidget(self.countLineEdit, 1, 1, 1, 1)
        self.rangeBox = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.rangeBox.setMinimumSize(QtCore.QSize(0, 24))
        self.rangeBox.setObjectName("rangeBox")
        self.gridLayout.addWidget(self.rangeBox, 2, 0, 1, 1)
        self.rangeLabel = QtWidgets.QLabel(self.gridLayoutWidget)
        self.rangeLabel.setEnabled(False)
        self.rangeLabel.setMinimumSize(QtCore.QSize(0, 24))
        self.rangeLabel.setObjectName("rangeLabel")
        self.gridLayout.addWidget(self.rangeLabel, 3, 0, 1, 1)
        self.rangeLineEdit = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.rangeLineEdit.setEnabled(False)
        self.rangeLineEdit.setMinimumSize(QtCore.QSize(0, 24))
        self.rangeLineEdit.setObjectName("rangeLineEdit")
        self.gridLayout.addWidget(self.rangeLineEdit, 3, 1, 1, 1)
        self.countBox = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.countBox.setMinimumSize(QtCore.QSize(0, 24))
        self.countBox.setObjectName("countBox")
        self.gridLayout.addWidget(self.countBox, 0, 0, 1, 1)
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(richnessDialog)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(130, 20, 421, 41))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.inputsLabel = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.inputsLabel.setMinimumSize(QtCore.QSize(24, 0))
        self.inputsLabel.setObjectName("inputsLabel")
        self.verticalLayout_2.addWidget(self.inputsLabel)

        self.retranslateUi(richnessDialog)
        self.cancelButton.clicked.connect(richnessDialog.close)
        self.countBox.clicked['bool'].connect(self.countLabel.setEnabled)
        self.countBox.clicked['bool'].connect(self.countLineEdit.setEnabled)
        self.rangeBox.clicked['bool'].connect(self.rangeLabel.setEnabled)
        self.rangeBox.clicked['bool'].connect(self.rangeLineEdit.setEnabled)
        QtCore.QMetaObject.connectSlotsByName(richnessDialog)

    def retranslateUi(self, richnessDialog):
        _translate = QtCore.QCoreApplication.translate
        richnessDialog.setWindowTitle(_translate("richnessDialog", "Calculate richness scores"))
        self.okButton.setText(_translate("richnessDialog", "OK"))
        self.cancelButton.setText(_translate("richnessDialog", "Cancel"))
        self.typeLabel.setText(_translate("richnessDialog", "Use features with type codes from the target file:"))
        self.countLabel.setText(_translate("richnessDialog", "Field name"))
        self.rangeBox.setText(_translate("richnessDialog", "Restricted Range Richness"))
        self.rangeLabel.setText(_translate("richnessDialog", "Field name"))
        self.countBox.setText(_translate("richnessDialog", "Feature Count"))
        self.inputsLabel.setText(_translate("richnessDialog", "Calculate the following for each planning unit:"))

import resources_rc

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    richnessDialog = QtWidgets.QDialog()
    ui = Ui_richnessDialog()
    ui.setupUi(richnessDialog)
    richnessDialog.show()
    sys.exit(app.exec_())

