# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\Bob\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\cluz3\forms\cluz_form_minpatch.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_minpatchDialog(object):
    def setupUi(self, minpatchDialog):
        minpatchDialog.setObjectName("minpatchDialog")
        minpatchDialog.resize(750, 470)
        minpatchDialog.setMinimumSize(QtCore.QSize(750, 470))
        self.logoLabel = QtWidgets.QLabel(minpatchDialog)
        self.logoLabel.setGeometry(QtCore.QRect(-10, 20, 120, 380))
        self.logoLabel.setText("")
        self.logoLabel.setPixmap(QtGui.QPixmap(":/images/images/setup_logo.png"))
        self.logoLabel.setObjectName("logoLabel")
        self.tabWidget = QtWidgets.QTabWidget(minpatchDialog)
        self.tabWidget.setGeometry(QtCore.QRect(130, 20, 591, 381))
        self.tabWidget.setObjectName("tabWidget")
        self.tab1 = QtWidgets.QWidget()
        self.tab1.setObjectName("tab1")
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(self.tab1)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(10, 100, 551, 41))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.minpatchFileLabel = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.minpatchFileLabel.setMinimumSize(QtCore.QSize(0, 24))
        self.minpatchFileLabel.setObjectName("minpatchFileLabel")
        self.horizontalLayout_2.addWidget(self.minpatchFileLabel)
        self.detailsLineEdit = QtWidgets.QLineEdit(self.horizontalLayoutWidget_2)
        self.detailsLineEdit.setMinimumSize(QtCore.QSize(0, 24))
        self.detailsLineEdit.setObjectName("detailsLineEdit")
        self.horizontalLayout_2.addWidget(self.detailsLineEdit)
        self.browseButton = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.browseButton.setMinimumSize(QtCore.QSize(0, 24))
        self.browseButton.setObjectName("browseButton")
        self.horizontalLayout_2.addWidget(self.browseButton)
        self.horizontalLayoutWidget_3 = QtWidgets.QWidget(self.tab1)
        self.horizontalLayoutWidget_3.setGeometry(QtCore.QRect(10, 150, 371, 41))
        self.horizontalLayoutWidget_3.setObjectName("horizontalLayoutWidget_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_3)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.listLabel_2 = QtWidgets.QLabel(self.horizontalLayoutWidget_3)
        self.listLabel_2.setMinimumSize(QtCore.QSize(0, 24))
        self.listLabel_2.setObjectName("listLabel_2")
        self.horizontalLayout_3.addWidget(self.listLabel_2)
        self.blmLineEdit = QtWidgets.QLineEdit(self.horizontalLayoutWidget_3)
        self.blmLineEdit.setMinimumSize(QtCore.QSize(0, 24))
        self.blmLineEdit.setObjectName("blmLineEdit")
        self.horizontalLayout_3.addWidget(self.blmLineEdit)
        self.fileListWidget = QtWidgets.QListWidget(self.tab1)
        self.fileListWidget.setGeometry(QtCore.QRect(10, 230, 561, 121))
        self.fileListWidget.setObjectName("fileListWidget")
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.tab1)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(10, 10, 551, 81))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.inputLabel = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.inputLabel.setMinimumSize(QtCore.QSize(0, 24))
        self.inputLabel.setObjectName("inputLabel")
        self.verticalLayout_2.addWidget(self.inputLabel)
        self.outputLabel = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.outputLabel.setMinimumSize(QtCore.QSize(0, 24))
        self.outputLabel.setObjectName("outputLabel")
        self.verticalLayout_2.addWidget(self.outputLabel)
        self.horizontalLayoutWidget_4 = QtWidgets.QWidget(self.tab1)
        self.horizontalLayoutWidget_4.setGeometry(QtCore.QRect(10, 200, 561, 31))
        self.horizontalLayoutWidget_4.setObjectName("horizontalLayoutWidget_4")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_4)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.listLabel = QtWidgets.QLabel(self.horizontalLayoutWidget_4)
        self.listLabel.setMinimumSize(QtCore.QSize(0, 24))
        self.listLabel.setObjectName("listLabel")
        self.horizontalLayout_4.addWidget(self.listLabel)
        self.tabWidget.addTab(self.tab1, "")
        self.tab2 = QtWidgets.QWidget()
        self.tab2.setObjectName("tab2")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.tab2)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 20, 561, 171))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.removeCheckBox = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        self.removeCheckBox.setChecked(True)
        self.removeCheckBox.setObjectName("removeCheckBox")
        self.verticalLayout.addWidget(self.removeCheckBox)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout.addItem(spacerItem)
        self.addCheckBox = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        self.addCheckBox.setChecked(True)
        self.addCheckBox.setObjectName("addCheckBox")
        self.verticalLayout.addWidget(self.addCheckBox)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout.addItem(spacerItem1)
        self.whittleCheckBox = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        self.whittleCheckBox.setChecked(True)
        self.whittleCheckBox.setObjectName("whittleCheckBox")
        self.verticalLayout.addWidget(self.whittleCheckBox)
        self.tabWidget.addTab(self.tab2, "")
        self.horizontalLayoutWidget = QtWidgets.QWidget(minpatchDialog)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(280, 410, 311, 41))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.startButton = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.startButton.setObjectName("startButton")
        self.horizontalLayout.addWidget(self.startButton)
        self.closeButton = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.closeButton.setObjectName("closeButton")
        self.horizontalLayout.addWidget(self.closeButton)

        self.retranslateUi(minpatchDialog)
        self.tabWidget.setCurrentIndex(0)
        self.closeButton.clicked.connect(minpatchDialog.close)
        QtCore.QMetaObject.connectSlotsByName(minpatchDialog)

    def retranslateUi(self, minpatchDialog):
        _translate = QtCore.QCoreApplication.translate
        minpatchDialog.setWindowTitle(_translate("minpatchDialog", "Launch MinPatch"))
        self.minpatchFileLabel.setText(_translate("minpatchDialog", "MinPatch details file"))
        self.browseButton.setText(_translate("minpatchDialog", "Browse"))
        self.listLabel_2.setText(_translate("minpatchDialog", "Boundary Length Modifier Value"))
        self.inputLabel.setText(_translate("minpatchDialog", "Marxan input folder:"))
        self.outputLabel.setText(_translate("minpatchDialog", "Marxan output folder:"))
        self.listLabel.setText(_translate("minpatchDialog", "Marxan files to analyse"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab1), _translate("minpatchDialog", "Standard options"))
        self.removeCheckBox.setText(_translate("minpatchDialog", "Remove small patches"))
        self.addCheckBox.setText(_translate("minpatchDialog", "Add patches"))
        self.whittleCheckBox.setText(_translate("minpatchDialog", "Simulated whittling"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab2), _translate("minpatchDialog", "Advanced options"))
        self.startButton.setText(_translate("minpatchDialog", "Start MinPatch"))
        self.closeButton.setText(_translate("minpatchDialog", "Close"))

import resources_rc

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    minpatchDialog = QtWidgets.QDialog()
    ui = Ui_minpatchDialog()
    ui.setupUi(minpatchDialog)
    minpatchDialog.show()
    sys.exit(app.exec_())

