# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\Bob\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\cluz3\forms\cluz_form_calibrate.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_calibrateDialog(object):
    def setupUi(self, calibrateDialog):
        calibrateDialog.setObjectName("calibrateDialog")
        calibrateDialog.resize(730, 523)
        calibrateDialog.setMinimumSize(QtCore.QSize(730, 0))
        self.label = QtWidgets.QLabel(calibrateDialog)
        self.label.setGeometry(QtCore.QRect(10, 0, 180, 380))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setMinimumSize(QtCore.QSize(150, 350))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap(":/images/images/marxan_logo.png"))
        self.label.setObjectName("label")
        self.horizontalLayoutWidget = QtWidgets.QWidget(calibrateDialog)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(320, 430, 201, 31))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.runButton = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.runButton.setMinimumSize(QtCore.QSize(0, 20))
        self.runButton.setObjectName("runButton")
        self.horizontalLayout.addWidget(self.runButton)
        self.closeButton = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.closeButton.setMinimumSize(QtCore.QSize(0, 20))
        self.closeButton.setObjectName("closeButton")
        self.horizontalLayout.addWidget(self.closeButton)
        self.formLayoutWidget = QtWidgets.QWidget(calibrateDialog)
        self.formLayoutWidget.setGeometry(QtCore.QRect(190, 30, 511, 111))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setFieldGrowthPolicy(QtWidgets.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.parameterLabel = QtWidgets.QLabel(self.formLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.parameterLabel.sizePolicy().hasHeightForWidth())
        self.parameterLabel.setSizePolicy(sizePolicy)
        self.parameterLabel.setMinimumSize(QtCore.QSize(110, 16))
        self.parameterLabel.setObjectName("parameterLabel")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.parameterLabel)
        self.paraComboBox = QtWidgets.QComboBox(self.formLayoutWidget)
        self.paraComboBox.setMinimumSize(QtCore.QSize(0, 20))
        self.paraComboBox.setObjectName("paraComboBox")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.paraComboBox)
        self.numberLabel = QtWidgets.QLabel(self.formLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.numberLabel.sizePolicy().hasHeightForWidth())
        self.numberLabel.setSizePolicy(sizePolicy)
        self.numberLabel.setMinimumSize(QtCore.QSize(110, 16))
        self.numberLabel.setObjectName("numberLabel")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.numberLabel)
        self.numberLineEdit = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.numberLineEdit.setMinimumSize(QtCore.QSize(0, 20))
        self.numberLineEdit.setObjectName("numberLineEdit")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.numberLineEdit)
        self.minLabel = QtWidgets.QLabel(self.formLayoutWidget)
        self.minLabel.setObjectName("minLabel")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.minLabel)
        self.minLineEdit = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.minLineEdit.setMinimumSize(QtCore.QSize(0, 20))
        self.minLineEdit.setObjectName("minLineEdit")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.minLineEdit)
        self.maxLabel = QtWidgets.QLabel(self.formLayoutWidget)
        self.maxLabel.setObjectName("maxLabel")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.maxLabel)
        self.maxLineEdit = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.maxLineEdit.setMinimumSize(QtCore.QSize(0, 20))
        self.maxLineEdit.setObjectName("maxLineEdit")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.maxLineEdit)
        self.expCheckBox = QtWidgets.QCheckBox(calibrateDialog)
        self.expCheckBox.setGeometry(QtCore.QRect(190, 150, 531, 20))
        self.expCheckBox.setMinimumSize(QtCore.QSize(0, 20))
        self.expCheckBox.setObjectName("expCheckBox")
        self.formLayoutWidget_2 = QtWidgets.QWidget(calibrateDialog)
        self.formLayoutWidget_2.setGeometry(QtCore.QRect(190, 190, 511, 91))
        self.formLayoutWidget_2.setObjectName("formLayoutWidget_2")
        self.formLayout_2 = QtWidgets.QFormLayout(self.formLayoutWidget_2)
        self.formLayout_2.setFieldGrowthPolicy(QtWidgets.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_2.setContentsMargins(0, 0, 0, 0)
        self.formLayout_2.setObjectName("formLayout_2")
        self.iterLabel = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.iterLabel.setObjectName("iterLabel")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.iterLabel)
        self.iterLineEdit = QtWidgets.QLineEdit(self.formLayoutWidget_2)
        self.iterLineEdit.setObjectName("iterLineEdit")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.iterLineEdit)
        self.runLabel = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.runLabel.setObjectName("runLabel")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.runLabel)
        self.runLineEdit = QtWidgets.QLineEdit(self.formLayoutWidget_2)
        self.runLineEdit.setObjectName("runLineEdit")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.runLineEdit)
        self.boundLabel = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.boundLabel.setObjectName("boundLabel")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.boundLabel)
        self.boundLineEdit = QtWidgets.QLineEdit(self.formLayoutWidget_2)
        self.boundLineEdit.setObjectName("boundLineEdit")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.boundLineEdit)
        self.formLayoutWidget_3 = QtWidgets.QWidget(calibrateDialog)
        self.formLayoutWidget_3.setGeometry(QtCore.QRect(190, 310, 511, 41))
        self.formLayoutWidget_3.setObjectName("formLayoutWidget_3")
        self.formLayout_3 = QtWidgets.QFormLayout(self.formLayoutWidget_3)
        self.formLayout_3.setFieldGrowthPolicy(QtWidgets.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_3.setContentsMargins(0, 0, 0, 0)
        self.formLayout_3.setObjectName("formLayout_3")
        self.outputLabel = QtWidgets.QLabel(self.formLayoutWidget_3)
        self.outputLabel.setMinimumSize(QtCore.QSize(0, 20))
        self.outputLabel.setObjectName("outputLabel")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.outputLabel)
        self.outputLineEdit = QtWidgets.QLineEdit(self.formLayoutWidget_3)
        self.outputLineEdit.setMinimumSize(QtCore.QSize(0, 20))
        self.outputLineEdit.setObjectName("outputLineEdit")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.outputLineEdit)
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(calibrateDialog)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(190, 360, 511, 41))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.resultsLabel = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.resultsLabel.setMinimumSize(QtCore.QSize(20, 0))
        self.resultsLabel.setObjectName("resultsLabel")
        self.horizontalLayout_2.addWidget(self.resultsLabel)
        self.resultsLineEdit = QtWidgets.QLineEdit(self.horizontalLayoutWidget_2)
        self.resultsLineEdit.setMinimumSize(QtCore.QSize(0, 20))
        self.resultsLineEdit.setObjectName("resultsLineEdit")
        self.horizontalLayout_2.addWidget(self.resultsLineEdit)
        self.saveResultsButton = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.saveResultsButton.setMinimumSize(QtCore.QSize(0, 20))
        self.saveResultsButton.setObjectName("saveResultsButton")
        self.horizontalLayout_2.addWidget(self.saveResultsButton)

        self.retranslateUi(calibrateDialog)
        self.closeButton.clicked.connect(calibrateDialog.close)
        QtCore.QMetaObject.connectSlotsByName(calibrateDialog)

    def retranslateUi(self, calibrateDialog):
        _translate = QtCore.QCoreApplication.translate
        calibrateDialog.setWindowTitle(_translate("calibrateDialog", "Calibrate Marxan parameters"))
        self.runButton.setText(_translate("calibrateDialog", "Run Analysis"))
        self.closeButton.setText(_translate("calibrateDialog", "Close"))
        self.parameterLabel.setText(_translate("calibrateDialog", "Parameter to calibrate"))
        self.numberLabel.setText(_translate("calibrateDialog", "Number of analyses"))
        self.minLabel.setText(_translate("calibrateDialog", "Minimum value"))
        self.maxLabel.setText(_translate("calibrateDialog", "Maximum value"))
        self.expCheckBox.setText(_translate("calibrateDialog", "Use exponential steps between minimum and maximum values"))
        self.iterLabel.setText(_translate("calibrateDialog", "Number of iterations"))
        self.runLabel.setText(_translate("calibrateDialog", "Number of runs"))
        self.boundLabel.setText(_translate("calibrateDialog", "BLM value"))
        self.outputLabel.setText(_translate("calibrateDialog", "Marxan output files base name     "))
        self.resultsLabel.setText(_translate("calibrateDialog", "Results file"))
        self.saveResultsButton.setText(_translate("calibrateDialog", "Save As..."))

import resources_rc

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    calibrateDialog = QtWidgets.QDialog()
    ui = Ui_calibrateDialog()
    ui.setupUi(calibrateDialog)
    calibrateDialog.show()
    sys.exit(app.exec_())

