# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\Bob\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\cluz3\forms\cluz_form_portfolio.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_portfolioDialog(object):
    def setupUi(self, portfolioDialog):
        portfolioDialog.setObjectName("portfolioDialog")
        portfolioDialog.resize(750, 400)
        portfolioDialog.setMinimumSize(QtCore.QSize(750, 400))
        portfolioDialog.setAutoFillBackground(True)
        self.logoLabel = QtWidgets.QLabel(portfolioDialog)
        self.logoLabel.setGeometry(QtCore.QRect(-10, 20, 120, 380))
        self.logoLabel.setText("")
        self.logoLabel.setPixmap(QtGui.QPixmap(":/images/images/setup_logo.png"))
        self.logoLabel.setObjectName("logoLabel")
        self.horizontalLayoutWidget = QtWidgets.QWidget(portfolioDialog)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(280, 350, 271, 41))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.okButton = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.okButton.setMinimumSize(QtCore.QSize(0, 24))
        self.okButton.setObjectName("okButton")
        self.horizontalLayout.addWidget(self.okButton)
        self.cancelButton = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.cancelButton.setMinimumSize(QtCore.QSize(0, 24))
        self.cancelButton.setObjectName("cancelButton")
        self.horizontalLayout.addWidget(self.cancelButton)
        self.layoutWidget = QtWidgets.QWidget(portfolioDialog)
        self.layoutWidget.setGeometry(QtCore.QRect(131, 20, 591, 311))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(6, 6, 6, 6)
        self.verticalLayout.setObjectName("verticalLayout")
        self.portfolioLabel = QtWidgets.QLabel(self.layoutWidget)
        self.portfolioLabel.setMaximumSize(QtCore.QSize(16777215, 20))
        self.portfolioLabel.setAutoFillBackground(True)
        self.portfolioLabel.setObjectName("portfolioLabel")
        self.verticalLayout.addWidget(self.portfolioLabel)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.puDetailsCheckBox = QtWidgets.QCheckBox(self.layoutWidget)
        self.puDetailsCheckBox.setChecked(True)
        self.puDetailsCheckBox.setObjectName("puDetailsCheckBox")
        self.verticalLayout_2.addWidget(self.puDetailsCheckBox)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout_2.addItem(spacerItem)
        self.spatialCheckBox = QtWidgets.QCheckBox(self.layoutWidget)
        self.spatialCheckBox.setChecked(True)
        self.spatialCheckBox.setObjectName("spatialCheckBox")
        self.verticalLayout_2.addWidget(self.spatialCheckBox)
        spacerItem1 = QtWidgets.QSpacerItem(40, 10, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout_2.addItem(spacerItem1)
        self.sfCheckBox = QtWidgets.QCheckBox(self.layoutWidget)
        self.sfCheckBox.setObjectName("sfCheckBox")
        self.verticalLayout_2.addWidget(self.sfCheckBox)
        self.formLayout_2 = QtWidgets.QFormLayout()
        self.formLayout_2.setFieldGrowthPolicy(QtWidgets.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_2.setContentsMargins(0, 0, 0, 0)
        self.formLayout_2.setObjectName("formLayout_2")
        self.sfFieldLabel = QtWidgets.QLabel(self.layoutWidget)
        self.sfFieldLabel.setObjectName("sfFieldLabel")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.sfFieldLabel)
        self.sfComboBox = QtWidgets.QComboBox(self.layoutWidget)
        self.sfComboBox.setMinimumSize(QtCore.QSize(0, 24))
        self.sfComboBox.setObjectName("sfComboBox")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.sfComboBox)
        self.formLayout_6 = QtWidgets.QFormLayout()
        self.formLayout_6.setFieldGrowthPolicy(QtWidgets.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_6.setObjectName("formLayout_6")
        self.sfRunsLabel = QtWidgets.QLabel(self.layoutWidget)
        self.sfRunsLabel.setTextFormat(QtCore.Qt.PlainText)
        self.sfRunsLabel.setWordWrap(True)
        self.sfRunsLabel.setObjectName("sfRunsLabel")
        self.formLayout_6.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.sfRunsLabel)
        self.sfRunsLineEdit = QtWidgets.QLineEdit(self.layoutWidget)
        self.sfRunsLineEdit.setMinimumSize(QtCore.QSize(0, 24))
        self.sfRunsLineEdit.setAutoFillBackground(True)
        self.sfRunsLineEdit.setObjectName("sfRunsLineEdit")
        self.formLayout_6.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.sfRunsLineEdit)
        self.formLayout_2.setLayout(2, QtWidgets.QFormLayout.LabelRole, self.formLayout_6)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.formLayout_2.setItem(3, QtWidgets.QFormLayout.LabelRole, spacerItem2)
        self.patchTargetCheckBox = QtWidgets.QCheckBox(self.layoutWidget)
        self.patchTargetCheckBox.setObjectName("patchTargetCheckBox")
        self.formLayout_2.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.patchTargetCheckBox)
        self.equalityCheckBox = QtWidgets.QCheckBox(self.layoutWidget)
        self.equalityCheckBox.setObjectName("equalityCheckBox")
        self.formLayout_2.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.equalityCheckBox)
        self.verticalLayout_2.addLayout(self.formLayout_2)
        self.verticalLayout.addLayout(self.verticalLayout_2)

        self.retranslateUi(portfolioDialog)
        self.cancelButton.clicked.connect(portfolioDialog.close)
        self.sfCheckBox.clicked['bool'].connect(self.sfComboBox.setEnabled)
        self.sfCheckBox.clicked['bool'].connect(self.sfRunsLineEdit.setVisible)
        self.sfCheckBox.clicked['bool'].connect(self.sfRunsLabel.setVisible)
        self.sfCheckBox.clicked['bool'].connect(self.sfFieldLabel.setEnabled)
        QtCore.QMetaObject.connectSlotsByName(portfolioDialog)

    def retranslateUi(self, portfolioDialog):
        _translate = QtCore.QCoreApplication.translate
        portfolioDialog.setWindowTitle(_translate("portfolioDialog", "Create Marxan files"))
        self.okButton.setText(_translate("portfolioDialog", "OK"))
        self.cancelButton.setText(_translate("portfolioDialog", "Cancel"))
        self.portfolioLabel.setText(_translate("portfolioDialog", "Calculate the following details about the current portfolio of planning units:"))
        self.puDetailsCheckBox.setText(_translate("portfolioDialog", "Planning unit details"))
        self.spatialCheckBox.setText(_translate("portfolioDialog", "Spatial details (patch sizes and boundary length)"))
        self.sfCheckBox.setText(_translate("portfolioDialog", "Selection frequency details of Available and Earmarked planning units"))
        self.sfFieldLabel.setText(_translate("portfolioDialog", "Field containing values"))
        self.sfRunsLabel.setText(_translate("portfolioDialog", "Number of runs used in analysis (ie maximum potential selection frequency)"))
        self.patchTargetCheckBox.setText(_translate("portfolioDialog", "Number of patches containing each conservation feature"))
        self.equalityCheckBox.setText(_translate("portfolioDialog", "Protection equality"))

import resources_rc

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    portfolioDialog = QtWidgets.QDialog()
    ui = Ui_portfolioDialog()
    ui.setupUi(portfolioDialog)
    portfolioDialog.show()
    sys.exit(app.exec_())

